server:
  port: 8092

spring:
  cloud:
    stream:
      default-binder: default_binder
      binders:
        default_binder:
          type: rabbit
          environment:
           spring:
            rabbitmq:
              host: 192.168.123.46
              port: 5672
              username: admin
              password: admin
              virtual-host: /
      bindings:
        cus-output1:
          destination: test-exchange


logging:
  config: classpath:log4j2.xml




